version: 2
jobs:
  build:
    docker:
      - image: visitdav/visit-ci-develop:current
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Submodule Init
          command: git submodule update --init --recursive
      - run:
          name: Test Build
          command: scripts/ci/circle/circle-test-visit-ci-develop.sh 
          no_output_timeout: 30m
